[package]
name = "sp1-aggregator"
version = "0.1.0"
authors = ["Automata Team"]
edition = "2021"
license = "Apache-2.0"

[workspace]

[dependencies]
alloy-sol-types = "1.0"
sp1-zkvm = { version = "^5.0.0", features = ["verify"] }
aws-nitro-enclave-attestation-verifier = { path = "../../verifier" }
alloy-primitives = "1.2"
